name: Lint and Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files --show-diff-on-failure

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        os_arch:
          - linux/amd64
          - darwin/amd64
          - windows/amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Build
        run: |
          OS_ARCH=${{ matrix.os_arch }}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          NAME=${{github.repository}}-$OS-$ARCH
          go build -o $NAME -v
